//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ_TPA_Program.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailCreation
    {
        public int Id { get; set; }
        public int HeaderId { get; set; }
        public int RideId { get; set; }
        public int Quantity { get; set; }
    
        public virtual HeaderCreation HeaderCreation { get; set; }
        public virtual Ride Ride { get; set; }
    }
}
