//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ_TPA_Program.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderConstruction
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int RideId { get; set; }
        public System.DateTime ConstructionRequestDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Ride Ride { get; set; }
    }
}
