//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ_TPA_Program.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderPurchaseRequest
    {
        public int Id { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string ResponseStatus { get; set; }
        public int ItemPieceId { get; set; }
        public int Quantity { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ItemPiece ItemPiece { get; set; }
    }
}
