//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ_TPA_Program.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ride
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ride()
        {
            this.DetailCreations = new HashSet<DetailCreation>();
            this.HeaderResponses = new HashSet<HeaderResponse>();
            this.HeaderConstructions = new HashSet<HeaderConstruction>();
            this.HeaderMaintenances = new HashSet<HeaderMaintenance>();
        }
    
        public int Id { get; set; }
        public string RideName { get; set; }
        public int RideDurabilityCheckPerWeek { get; set; }
        public string RideStatus { get; set; }
        public string RideMaintainStatus { get; set; }
        public int RideTypeId { get; set; }
        public int RideSafetyId { get; set; }
        public int RideForce { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailCreation> DetailCreations { get; set; }
        public virtual RideSafety RideSafety { get; set; }
        public virtual RideType RideType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeaderResponse> HeaderResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeaderConstruction> HeaderConstructions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeaderMaintenance> HeaderMaintenances { get; set; }
    }
}
